services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./api/assets:/app/assets 
    depends_on:
      - postgres
    restart: always
    env_file:
      - ./api/.env
    environment:
      - DB_SOURCE=postgresql://url:url@postgres:5432/postgres?sslmode=disable
    dns:
      - 8.8.8.8
      - 1.1.1.1

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: url
      POSTGRES_PASSWORD: url
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
