// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type QrCode struct {
	ID        int32          `json:"id"`
	UrlID     int32          `json:"url_id"`
	QrCode    string         `json:"qr_code"`
	FgColor   sql.NullString `json:"fg_color"`
	BgColor   sql.NullString `json:"bg_color"`
	ExpireAt  sql.NullTime   `json:"expire_at"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Url struct {
	ID           int32          `json:"id"`
	OriginalUrl  string         `json:"original_url"`
	Title        sql.NullString `json:"title"`
	ShortCode    string         `json:"short_code"`
	Thumbnail    sql.NullString `json:"thumbnail"`
	ClickCount   int32          `json:"click_count"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	ExpireAt     sql.NullTime   `json:"expire_at"`
	UserID       sql.NullInt32  `json:"user_id"`
}

type UrlVisit struct {
	ID         int32          `json:"id"`
	UrlID      int32          `json:"url_id"`
	UserID     sql.NullInt32  `json:"user_id"`
	IpAddress  string         `json:"ip_address"`
	UserAgent  string         `json:"user_agent"`
	DeviceType sql.NullString `json:"device_type"`
	Referrer   sql.NullString `json:"referrer"`
	Country    sql.NullString `json:"country"`
	Region     sql.NullString `json:"region"`
	City       sql.NullString `json:"city"`
	ClickedAt  sql.NullTime   `json:"clicked_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	IpAddress    string         `json:"ip_address"`
	Provider     sql.NullString `json:"provider"`
	ProviderID   sql.NullString `json:"provider_id"`
	Image        sql.NullString `json:"image"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
