// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Url struct {
	ID          int32        `json:"id"`
	OriginalUrl string       `json:"original_url"`
	ShortCode   string       `json:"short_code"`
	ClickCount  int32        `json:"click_count"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	IpAddress    string         `json:"ip_address"`
	Provider     string         `json:"provider"`
	ProviderID   string         `json:"provider_id"`
	Image        sql.NullString `json:"image"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}
