// Code generated by tygo. DO NOT EDIT.

//////////
// source: analytics.go

export interface AnalyticsRequest {
  shortcode: string;
}
export interface AnalyticsResponse {
  shortcode: string;
  click_count: number /* int64 */;
  original_url: string;
  clicked_at: string;
  user_id?: number /* int32 */;
  visits: VisitAnalyticsItem[];
}
export interface VisitAnalyticsItem {
  ip_address: string;
  user_agent: string;
  referrer: string;
  country: string;
  region: string;
  city: string;
  timestamp: string;
}

//////////
// source: qr.go

export interface QRCodeRequest {
  original_url: string;
  expiry_days: number /* int */;
}
export interface QRCodeResponse {
  short_url: string;
  qrcode: string;
}
/**
 * #TODO: Add user logo link struct ****premium feature****
 */
export interface QRCodeWithLogoRequest {
  original_url: string;
  shortcode?: string;
  logo_url?: string;
  fg_color?: string;
  bg_color?: string;
  format?: string; // e.g., "png", "jpeg"
  expire_at?: number /* int */;
}

//////////
// source: url.go

export interface ShortURLRequest {
  original_url: string;
  shortcode?: string;
  title?: string;
  password?: string;
  expire_at?: string;
}
export interface ShortURLResponse {
  short_url: string;
  thumbnail?: string;
  format?: string;
}
export interface EditURLRequest {
  title: string;
  original_url: string;
  expire_at: string;
  password: string;
}
export interface LinkResponse {
  id: number /* int64 */;
  title: string;
  original_url: string;
  short_url: string;
  clicks: number /* int */;
  created_at: string;
  thumbnail?: string;
  expire_at?: string;
  password?: boolean;
}
