services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./assets:/app/assets 
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - DB_SOURCE=postgresql://url:url@postgres:5432/postgres?sslmode=disable

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: url
      POSTGRES_PASSWORD: url
      POSTGRES_HOST_AUTH_METHOD: trust 
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql:ro
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  
